language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-interactive' ]; then cd .. && eval "mv $currentfolder generator-interactive" && cd generator-interactive; fi

